export { default as Landing } from './Landing'
export { default as HomeLayout } from './HomeLayout'
export { default as About } from './About'
export { default as Projects } from './Projects'
export { default as Contact1 } from './Contact1'
export { default as Error } from './Error'
export { default as SinglePageError } from './SinglePageError'
